### ISSUE TITLE
How to estimate stochastic volatility from TVP-VAR model?

### ISSUE THREAD

**Issue by dbcwicaksono** [FK83/bvarsv#11]
Thanks for your contribution.
How to estimate stochastic volatility from TVP-VAR model?
I want to make graphs like this one: [https://www.researchgate.net/figure/Estimated-stochastic-volatility-from-the-TVP-VAR-Model-a-Variance-of-errors-in-interest_fig2_308036119](https://www.researchgate.net/figure/Estimated-stochastic-volatility-from-the-TVP-VAR-Model-a-Variance-of-errors-in-interest_fig2_308036119).

Thank you.

**Comment by FK83** [comment]
Hi,
 
this document shows some example time series plots of time-varying volatility: <https://github.com/FK83/bvarsv/blob/master/bvarsv_replication.pdf>

Best regards,
Fabian
