### ISSUE TITLE
A general question on using bvarsv on nonstationary data - won't take you long

### ISSUE THREAD

**Issue by yellowmonkey2** [FK83/bvarsv#13]
Hi Fabian,

Thank you so much for creating the fabulous package.

The primiceri paper directly used 3 variables, from which some are nonstationary.

This leads me to think " Can we directly use nonstationary data into the package ? "

Appreciate your answers!

Best
Chen

**Comment by TyroLiu** [comment]
> Hi Fabian,
> 
> Thank you so much for creating the fabulous package.
> 
> The primiceri paper directly used 3 variables, from which some are nonstationary.
> 
> This leads me to think " Can we directly use nonstationary data into the package ? "
> 
> Appreciate your answers!
> 
> Best Chen

I am thinking about the same question. The dataset provided by the package, "usmacro", has three variables that are all nonstationary. Their p-values of Augmented Dickey-Fuller Test are 0.4865, 0.3525, and 0.261, respectively. Theory tells us that time-series must be stationary for VAR estimation. Can we really use nonstationary series in the TVP-VAR model?
![image](https://github.com/FK83/bvarsv/assets/50902086/691e261f-dbd4-4fdf-a14c-e8c8ebf6f478)
