### ISSUE TITLE
Model in log-levels-error

### ISSUE THREAD

**Issue by michall23full** [FK83/bvarsv#2]
Hello, thanks for your hard work with bvarsv package. I regret to report a problem with it. Consistently with the approach suggested by Sims et al. (1990) I try to estimate my TVP-VAR in log-levels but I get the following error:

error: chol(): decomposition failed
Error in carterkohn(y, Z, Ht, Qdraw, K, M, t, B_0_prmean, B_0_prvar) : 
  chol(): decomposition failed

Another time I got following error:
Error in rWishart(1, t + Q_prvar, solve(sse_2 + Q_prmean)) : 
  matrix 'scal' is not positive definite

I would be very grateful for your advice,

**Comment by FK83** [comment]
Hi, thanks for the kind note. What is the approximate scale of your data (mean, standard deviation of each variable)? It seems like some of the prior parameters are scale-dependent, and there may be numerical problems when the scale of the data is very different from the Primiceri data in data("usmacro"). So maybe it helps to simply rescale your data.

**Comment by michall23full** [comment]
Oh, thanks for your answer. In my baseline dataset the data have mean around 400 (as they are in 100*ln(x)) form except interest rate (it is in level and varies from 1,6 to 30%). I tried also with the the data in log form without multiplying and it also resulted with the error

**Comment by FK83** [comment]
Hm...how many variables and lags do you include? Are the variables trending over time?

**Comment by michall23full** [comment]
I have oil price, prouction of total industry, CPI price level, 3-month interest rate and NEER.

They are non-stationary, but there are rather stochastic trends than deterministic

**Comment by FK83** [comment]
Do you use one lag (p = 1)? Since five variables implies many parameters to be estimated, you could try to restrict time variation in the mean equation parameters further, by setting pQ to values bigger than 40 (the default, if a training sample of length tau = 40 is used). I would also use the log form data without multiplying, such that all included variables have a similar mean.

**Comment by michall23full** [comment]
I orignally used 3 lags. but I retried with p=1 and various pQ  and log form as you recommended but it also failed. The difference is that with such changes the error occurs after a few hundred of draws. I also got an error with Cholesky decomposition from another function:

Error in getfcsts(lastcol(Btdraw), lastcol(Atdraw), lastcol(Sigtdraw),  : 
  chol(): decomposition failed

**Comment by michall23full** [comment]
I have set pQ to the size of my training sample and also have changed also the prior parameters k_W, k_S, k_Q in order to allow for more time variation and it works with 1 lag, but still not with 2 lags or more. So, I will probably estimate my model with 1 lag.

**Comment by FK83** [comment]
The choice for pQ seems reasonable. Regarding k_W, k_S and k_Q: In my experience, numerical problems (like failed Cholesky or failed inversion) are often a result of too much time variation, so it would seem more intuitive to restrict time variation...have you tried that as well? Apart from that, I agree that a parsimonious model with 1 lag only is a good choice here.

**Comment by michall23full** [comment]
Actually I set k_Q=0.05, k_W=0.01 and k_S=0.01. The choice was based on the study of related literature, where log-level data were analysed.

**Comment by FK83** [comment]
Okay, thanks - I'm closing the topic. In summary, my take is that to avoid numerical issues, the model should be specified as parsimoniously as possible, especially if the number of system variables is larger than in the original paper (which features three system variables).
