### ISSUE TITLE
Long run responses

### ISSUE THREAD

**Issue by lemuelemos** [FK83/bvarsv#3]
In the article of 2005, you plot a grafic with the response to 1% permanent increase of inflation. How you draw these? Is the parameters draws? How is the logic behind the simultaneous response and after 10,20 60 quarters?

**Comment by FK83** [comment]
[Here](https://github.com/FK83/bvarsv/blob/master/bvarsv_replication.pdf) is some code for replicating the impulse responses (though not the permanent ones) from Del Negro and Primiceri (2015), which is the correction of Primiceri (2005).

Maybe you can adjust the code to replicate the permanent impulse responses (I didn't try that one).
